Got first Spock test working: Hello World example
jmeter-gradle-plugin/jmeter-gradle-plugin pull request #88
Opened 2017-01-12 18:34 UTC by djangofan

Hi, a long time back I said I was interested in unit testing your pluging  (see https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin/issues/16  )   and so, I am creating this pull request for you to look at to see if I am going in the right direction for you?

2017-01-20 21:02 UTC, foragerr commented
@djangofan Thanks for helping out with tests! I'm not an expert in the area and cant give you a lot of direction. Just a few quick high level thoughts, feel free to tell me I'm wrong:

* Spock definitely seems to be the right way to go.
* gradle test kit is what other gradle plugins are using to build tests
* Maybe you should not add idea specific config to the repo. Feel free to use it locally but don't check them in

2017-08-10 15:35 UTC, romankh3 commented
I'm using Spoke in on of my projects and I want to say that this framework is deeper than JUnit4/5 for testing. It's a BDD concept.

2017-08-10 15:42 UTC, romankh3 requested changes
There is a good idea to add Spoke for testing!
For it needs work. Also, the build is red.

2017-08-10 15:42 UTC, romankh3 commented on src/test/groovy/net/foragerr/jmeter/gradle/plugins/HelloSpockSpec.groovy
> +class HelloSpockSpec extends spock.lang.Specification {
I think import will be better.

2017-08-10 15:42 UTC, romankh3 commented on build.gradle
> +            'org.spockframework:spock-core:1.1-groovy-2.4-rc-3',
you can update version of the Spoke to `1.1-groovy-2.4`. Now it's available.

2018-08-22 04:48 UTC, closed without merging